CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (
  id UUID UNIQUE PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
  email VARCHAR,
  password VARCHAR,
  datacriacao TIMESTAMPTZ DEFAULT NOW()
);
